apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-eloverblik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-eloverblik-deployment
  template:
    metadata:
      labels:
        app: fake-eloverblik-deployment
    spec:
      containers:
        - name: fake-eloverblik-container
          image: projectorigin/fake-eloverblik:{{ .Values.tag }}
          ports:
            - containerPort: 8765
          envFrom:
            - configMapRef:
                name: namespace-config
            - secretRef:
                name: fake-eloverblik-db-secret
            - configMapRef:
                name: fake-eloverblik-config
