"""empty message

Revision ID: 47527f0713be
Revises: 40023851c0f9
Create Date: 2020-10-28 09:51:08.267404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47527f0713be'
down_revision = '40023851c0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteringpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('gsrn', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('production', 'consumption', name='meteringpointtype'), nullable=False),
    sa.Column('technology_code', sa.String(), nullable=False),
    sa.Column('fuel_code', sa.String(), nullable=False),
    sa.Column('street_code', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('building_number', sa.String(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('municipality_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gsrn')
    )
    op.create_index(op.f('ix_meteringpoint_gsrn'), 'meteringpoint', ['gsrn'], unique=False)
    op.create_index(op.f('ix_meteringpoint_id'), 'meteringpoint', ['id'], unique=False)
    op.create_index(op.f('ix_meteringpoint_subject'), 'meteringpoint', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meteringpoint_subject'), table_name='meteringpoint')
    op.drop_index(op.f('ix_meteringpoint_id'), table_name='meteringpoint')
    op.drop_index(op.f('ix_meteringpoint_gsrn'), table_name='meteringpoint')
    op.drop_table('meteringpoint')
    # ### end Alembic commands ###
