"""empty message

Revision ID: 74d1120f4415
Revises: 47527f0713be
Create Date: 2020-10-30 09:48:42.803706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d1120f4415'
down_revision = '47527f0713be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meteringpoint', 'fuel_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('meteringpoint', 'technology_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meteringpoint', 'technology_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meteringpoint', 'fuel_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
